// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RMRHeader.proto

package org.godhuli.rhipe;

public final class RMRHeaderProtos {
  private RMRHeaderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum RhipeMode
      implements com.google.protobuf.ProtocolMessageEnum {
    MAPPER(0, 1),
    REDUCER(1, 2),
    ;
    
    public static final int MAPPER_VALUE = 1;
    public static final int REDUCER_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static RhipeMode valueOf(int value) {
      switch (value) {
        case 1: return MAPPER;
        case 2: return REDUCER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RhipeMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RhipeMode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RhipeMode>() {
            public RhipeMode findValueByNumber(int number) {
              return RhipeMode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.godhuli.rhipe.RMRHeaderProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final RhipeMode[] VALUES = {
      MAPPER, REDUCER, 
    };
    
    public static RhipeMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RhipeMode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:RhipeMode)
  }
  
  public enum CombinerMode
      implements com.google.protobuf.ProtocolMessageEnum {
    NO_COMBINER(0, 0),
    USE_COMBINER(1, 1),
    ;
    
    public static final int NO_COMBINER_VALUE = 0;
    public static final int USE_COMBINER_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static CombinerMode valueOf(int value) {
      switch (value) {
        case 0: return NO_COMBINER;
        case 1: return USE_COMBINER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CombinerMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CombinerMode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CombinerMode>() {
            public CombinerMode findValueByNumber(int number) {
              return CombinerMode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.godhuli.rhipe.RMRHeaderProtos.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final CombinerMode[] VALUES = {
      NO_COMBINER, USE_COMBINER, 
    };
    
    public static CombinerMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CombinerMode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:CombinerMode)
  }
  
  public interface ParameterPairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class ParameterPair extends
      com.google.protobuf.GeneratedMessage
      implements ParameterPairOrBuilder {
    // Use ParameterPair.newBuilder() to construct.
    private ParameterPair(Builder builder) {
      super(builder);
    }
    private ParameterPair(boolean noInit) {}
    
    private static final ParameterPair defaultInstance;
    public static ParameterPair getDefaultInstance() {
      return defaultInstance;
    }
    
    public ParameterPair getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.godhuli.rhipe.RMRHeaderProtos.internal_static_ParameterPair_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.godhuli.rhipe.RMRHeaderProtos.internal_static_ParameterPair_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.ParameterPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.godhuli.rhipe.RMRHeaderProtos.ParameterPair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.godhuli.rhipe.RMRHeaderProtos.internal_static_ParameterPair_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.godhuli.rhipe.RMRHeaderProtos.internal_static_ParameterPair_fieldAccessorTable;
      }
      
      // Construct using org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDescriptor();
      }
      
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getDefaultInstanceForType() {
        return org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDefaultInstance();
      }
      
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair build() {
        org.godhuli.rhipe.RMRHeaderProtos.ParameterPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.godhuli.rhipe.RMRHeaderProtos.ParameterPair buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.godhuli.rhipe.RMRHeaderProtos.ParameterPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair buildPartial() {
        org.godhuli.rhipe.RMRHeaderProtos.ParameterPair result = new org.godhuli.rhipe.RMRHeaderProtos.ParameterPair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.godhuli.rhipe.RMRHeaderProtos.ParameterPair) {
          return mergeFrom((org.godhuli.rhipe.RMRHeaderProtos.ParameterPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.godhuli.rhipe.RMRHeaderProtos.ParameterPair other) {
        if (other == org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ParameterPair)
    }
    
    static {
      defaultInstance = new ParameterPair(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ParameterPair)
  }
  
  public interface RMRHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string ID = 1;
    boolean hasID();
    String getID();
    
    // optional .RhipeMode RHIPEWHAT = 2;
    boolean hasRHIPEWHAT();
    org.godhuli.rhipe.RMRHeaderProtos.RhipeMode getRHIPEWHAT();
    
    // optional string RHIPELOGFILE = 3;
    boolean hasRHIPELOGFILE();
    String getRHIPELOGFILE();
    
    // optional string rhipe_outputformat_class = 12;
    boolean hasRhipeOutputformatClass();
    String getRhipeOutputformatClass();
    
    // optional .CombinerMode rhipe_combiner = 13;
    boolean hasRhipeCombiner();
    org.godhuli.rhipe.RMRHeaderProtos.CombinerMode getRhipeCombiner();
    
    // optional int32 rhipe_map_buff_size = 14;
    boolean hasRhipeMapBuffSize();
    int getRhipeMapBuffSize();
    
    // optional int32 rhipe_map_bytes_read = 15;
    boolean hasRhipeMapBytesRead();
    int getRhipeMapBytesRead();
    
    // repeated .ParameterPair serialized_assignments = 16;
    java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> 
        getSerializedAssignmentsList();
    org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getSerializedAssignments(int index);
    int getSerializedAssignmentsCount();
    java.util.List<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
        getSerializedAssignmentsOrBuilderList();
    org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder getSerializedAssignmentsOrBuilder(
        int index);
    
    // repeated .ParameterPair arguments = 17;
    java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> 
        getArgumentsList();
    org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getArguments(int index);
    int getArgumentsCount();
    java.util.List<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
        getArgumentsOrBuilderList();
    org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder getArgumentsOrBuilder(
        int index);
  }
  public static final class RMRHeader extends
      com.google.protobuf.GeneratedMessage
      implements RMRHeaderOrBuilder {
    // Use RMRHeader.newBuilder() to construct.
    private RMRHeader(Builder builder) {
      super(builder);
    }
    private RMRHeader(boolean noInit) {}
    
    private static final RMRHeader defaultInstance;
    public static RMRHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public RMRHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.godhuli.rhipe.RMRHeaderProtos.internal_static_RMRHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.godhuli.rhipe.RMRHeaderProtos.internal_static_RMRHeader_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string ID = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object iD_;
    public boolean hasID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getID() {
      java.lang.Object ref = iD_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iD_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIDBytes() {
      java.lang.Object ref = iD_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .RhipeMode RHIPEWHAT = 2;
    public static final int RHIPEWHAT_FIELD_NUMBER = 2;
    private org.godhuli.rhipe.RMRHeaderProtos.RhipeMode rHIPEWHAT_;
    public boolean hasRHIPEWHAT() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.godhuli.rhipe.RMRHeaderProtos.RhipeMode getRHIPEWHAT() {
      return rHIPEWHAT_;
    }
    
    // optional string RHIPELOGFILE = 3;
    public static final int RHIPELOGFILE_FIELD_NUMBER = 3;
    private java.lang.Object rHIPELOGFILE_;
    public boolean hasRHIPELOGFILE() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getRHIPELOGFILE() {
      java.lang.Object ref = rHIPELOGFILE_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rHIPELOGFILE_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRHIPELOGFILEBytes() {
      java.lang.Object ref = rHIPELOGFILE_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rHIPELOGFILE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string rhipe_outputformat_class = 12;
    public static final int RHIPE_OUTPUTFORMAT_CLASS_FIELD_NUMBER = 12;
    private java.lang.Object rhipeOutputformatClass_;
    public boolean hasRhipeOutputformatClass() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getRhipeOutputformatClass() {
      java.lang.Object ref = rhipeOutputformatClass_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rhipeOutputformatClass_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRhipeOutputformatClassBytes() {
      java.lang.Object ref = rhipeOutputformatClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rhipeOutputformatClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .CombinerMode rhipe_combiner = 13;
    public static final int RHIPE_COMBINER_FIELD_NUMBER = 13;
    private org.godhuli.rhipe.RMRHeaderProtos.CombinerMode rhipeCombiner_;
    public boolean hasRhipeCombiner() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public org.godhuli.rhipe.RMRHeaderProtos.CombinerMode getRhipeCombiner() {
      return rhipeCombiner_;
    }
    
    // optional int32 rhipe_map_buff_size = 14;
    public static final int RHIPE_MAP_BUFF_SIZE_FIELD_NUMBER = 14;
    private int rhipeMapBuffSize_;
    public boolean hasRhipeMapBuffSize() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getRhipeMapBuffSize() {
      return rhipeMapBuffSize_;
    }
    
    // optional int32 rhipe_map_bytes_read = 15;
    public static final int RHIPE_MAP_BYTES_READ_FIELD_NUMBER = 15;
    private int rhipeMapBytesRead_;
    public boolean hasRhipeMapBytesRead() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getRhipeMapBytesRead() {
      return rhipeMapBytesRead_;
    }
    
    // repeated .ParameterPair serialized_assignments = 16;
    public static final int SERIALIZED_ASSIGNMENTS_FIELD_NUMBER = 16;
    private java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> serializedAssignments_;
    public java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> getSerializedAssignmentsList() {
      return serializedAssignments_;
    }
    public java.util.List<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
        getSerializedAssignmentsOrBuilderList() {
      return serializedAssignments_;
    }
    public int getSerializedAssignmentsCount() {
      return serializedAssignments_.size();
    }
    public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getSerializedAssignments(int index) {
      return serializedAssignments_.get(index);
    }
    public org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder getSerializedAssignmentsOrBuilder(
        int index) {
      return serializedAssignments_.get(index);
    }
    
    // repeated .ParameterPair arguments = 17;
    public static final int ARGUMENTS_FIELD_NUMBER = 17;
    private java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> arguments_;
    public java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> getArgumentsList() {
      return arguments_;
    }
    public java.util.List<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
        getArgumentsOrBuilderList() {
      return arguments_;
    }
    public int getArgumentsCount() {
      return arguments_.size();
    }
    public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getArguments(int index) {
      return arguments_.get(index);
    }
    public org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder getArgumentsOrBuilder(
        int index) {
      return arguments_.get(index);
    }
    
    private void initFields() {
      iD_ = "";
      rHIPEWHAT_ = org.godhuli.rhipe.RMRHeaderProtos.RhipeMode.MAPPER;
      rHIPELOGFILE_ = "";
      rhipeOutputformatClass_ = "";
      rhipeCombiner_ = org.godhuli.rhipe.RMRHeaderProtos.CombinerMode.NO_COMBINER;
      rhipeMapBuffSize_ = 0;
      rhipeMapBytesRead_ = 0;
      serializedAssignments_ = java.util.Collections.emptyList();
      arguments_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSerializedAssignmentsCount(); i++) {
        if (!getSerializedAssignments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getArgumentsCount(); i++) {
        if (!getArguments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, rHIPEWHAT_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRHIPELOGFILEBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(12, getRhipeOutputformatClassBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(13, rhipeCombiner_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(14, rhipeMapBuffSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(15, rhipeMapBytesRead_);
      }
      for (int i = 0; i < serializedAssignments_.size(); i++) {
        output.writeMessage(16, serializedAssignments_.get(i));
      }
      for (int i = 0; i < arguments_.size(); i++) {
        output.writeMessage(17, arguments_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, rHIPEWHAT_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRHIPELOGFILEBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getRhipeOutputformatClassBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(13, rhipeCombiner_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, rhipeMapBuffSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, rhipeMapBytesRead_);
      }
      for (int i = 0; i < serializedAssignments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, serializedAssignments_.get(i));
      }
      for (int i = 0; i < arguments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, arguments_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.godhuli.rhipe.RMRHeaderProtos.RMRHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.godhuli.rhipe.RMRHeaderProtos.RMRHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.godhuli.rhipe.RMRHeaderProtos.RMRHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.godhuli.rhipe.RMRHeaderProtos.internal_static_RMRHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.godhuli.rhipe.RMRHeaderProtos.internal_static_RMRHeader_fieldAccessorTable;
      }
      
      // Construct using org.godhuli.rhipe.RMRHeaderProtos.RMRHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSerializedAssignmentsFieldBuilder();
          getArgumentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        iD_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        rHIPEWHAT_ = org.godhuli.rhipe.RMRHeaderProtos.RhipeMode.MAPPER;
        bitField0_ = (bitField0_ & ~0x00000002);
        rHIPELOGFILE_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        rhipeOutputformatClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        rhipeCombiner_ = org.godhuli.rhipe.RMRHeaderProtos.CombinerMode.NO_COMBINER;
        bitField0_ = (bitField0_ & ~0x00000010);
        rhipeMapBuffSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rhipeMapBytesRead_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (serializedAssignmentsBuilder_ == null) {
          serializedAssignments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          serializedAssignmentsBuilder_.clear();
        }
        if (argumentsBuilder_ == null) {
          arguments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          argumentsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.godhuli.rhipe.RMRHeaderProtos.RMRHeader.getDescriptor();
      }
      
      public org.godhuli.rhipe.RMRHeaderProtos.RMRHeader getDefaultInstanceForType() {
        return org.godhuli.rhipe.RMRHeaderProtos.RMRHeader.getDefaultInstance();
      }
      
      public org.godhuli.rhipe.RMRHeaderProtos.RMRHeader build() {
        org.godhuli.rhipe.RMRHeaderProtos.RMRHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.godhuli.rhipe.RMRHeaderProtos.RMRHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.godhuli.rhipe.RMRHeaderProtos.RMRHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.godhuli.rhipe.RMRHeaderProtos.RMRHeader buildPartial() {
        org.godhuli.rhipe.RMRHeaderProtos.RMRHeader result = new org.godhuli.rhipe.RMRHeaderProtos.RMRHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rHIPEWHAT_ = rHIPEWHAT_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rHIPELOGFILE_ = rHIPELOGFILE_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rhipeOutputformatClass_ = rhipeOutputformatClass_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.rhipeCombiner_ = rhipeCombiner_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rhipeMapBuffSize_ = rhipeMapBuffSize_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.rhipeMapBytesRead_ = rhipeMapBytesRead_;
        if (serializedAssignmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            serializedAssignments_ = java.util.Collections.unmodifiableList(serializedAssignments_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.serializedAssignments_ = serializedAssignments_;
        } else {
          result.serializedAssignments_ = serializedAssignmentsBuilder_.build();
        }
        if (argumentsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            arguments_ = java.util.Collections.unmodifiableList(arguments_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.arguments_ = arguments_;
        } else {
          result.arguments_ = argumentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.godhuli.rhipe.RMRHeaderProtos.RMRHeader) {
          return mergeFrom((org.godhuli.rhipe.RMRHeaderProtos.RMRHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.godhuli.rhipe.RMRHeaderProtos.RMRHeader other) {
        if (other == org.godhuli.rhipe.RMRHeaderProtos.RMRHeader.getDefaultInstance()) return this;
        if (other.hasID()) {
          setID(other.getID());
        }
        if (other.hasRHIPEWHAT()) {
          setRHIPEWHAT(other.getRHIPEWHAT());
        }
        if (other.hasRHIPELOGFILE()) {
          setRHIPELOGFILE(other.getRHIPELOGFILE());
        }
        if (other.hasRhipeOutputformatClass()) {
          setRhipeOutputformatClass(other.getRhipeOutputformatClass());
        }
        if (other.hasRhipeCombiner()) {
          setRhipeCombiner(other.getRhipeCombiner());
        }
        if (other.hasRhipeMapBuffSize()) {
          setRhipeMapBuffSize(other.getRhipeMapBuffSize());
        }
        if (other.hasRhipeMapBytesRead()) {
          setRhipeMapBytesRead(other.getRhipeMapBytesRead());
        }
        if (serializedAssignmentsBuilder_ == null) {
          if (!other.serializedAssignments_.isEmpty()) {
            if (serializedAssignments_.isEmpty()) {
              serializedAssignments_ = other.serializedAssignments_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureSerializedAssignmentsIsMutable();
              serializedAssignments_.addAll(other.serializedAssignments_);
            }
            onChanged();
          }
        } else {
          if (!other.serializedAssignments_.isEmpty()) {
            if (serializedAssignmentsBuilder_.isEmpty()) {
              serializedAssignmentsBuilder_.dispose();
              serializedAssignmentsBuilder_ = null;
              serializedAssignments_ = other.serializedAssignments_;
              bitField0_ = (bitField0_ & ~0x00000080);
              serializedAssignmentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSerializedAssignmentsFieldBuilder() : null;
            } else {
              serializedAssignmentsBuilder_.addAllMessages(other.serializedAssignments_);
            }
          }
        }
        if (argumentsBuilder_ == null) {
          if (!other.arguments_.isEmpty()) {
            if (arguments_.isEmpty()) {
              arguments_ = other.arguments_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureArgumentsIsMutable();
              arguments_.addAll(other.arguments_);
            }
            onChanged();
          }
        } else {
          if (!other.arguments_.isEmpty()) {
            if (argumentsBuilder_.isEmpty()) {
              argumentsBuilder_.dispose();
              argumentsBuilder_ = null;
              arguments_ = other.arguments_;
              bitField0_ = (bitField0_ & ~0x00000100);
              argumentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArgumentsFieldBuilder() : null;
            } else {
              argumentsBuilder_.addAllMessages(other.arguments_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasID()) {
          
          return false;
        }
        for (int i = 0; i < getSerializedAssignmentsCount(); i++) {
          if (!getSerializedAssignments(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getArgumentsCount(); i++) {
          if (!getArguments(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              iD_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.godhuli.rhipe.RMRHeaderProtos.RhipeMode value = org.godhuli.rhipe.RMRHeaderProtos.RhipeMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                rHIPEWHAT_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              rHIPELOGFILE_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000008;
              rhipeOutputformatClass_ = input.readBytes();
              break;
            }
            case 104: {
              int rawValue = input.readEnum();
              org.godhuli.rhipe.RMRHeaderProtos.CombinerMode value = org.godhuli.rhipe.RMRHeaderProtos.CombinerMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(13, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                rhipeCombiner_ = value;
              }
              break;
            }
            case 112: {
              bitField0_ |= 0x00000020;
              rhipeMapBuffSize_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000040;
              rhipeMapBytesRead_ = input.readInt32();
              break;
            }
            case 130: {
              org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder subBuilder = org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSerializedAssignments(subBuilder.buildPartial());
              break;
            }
            case 138: {
              org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder subBuilder = org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addArguments(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string ID = 1;
      private java.lang.Object iD_ = "";
      public boolean hasID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getID() {
        java.lang.Object ref = iD_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iD_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
        return this;
      }
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = getDefaultInstance().getID();
        onChanged();
        return this;
      }
      void setID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
      }
      
      // optional .RhipeMode RHIPEWHAT = 2;
      private org.godhuli.rhipe.RMRHeaderProtos.RhipeMode rHIPEWHAT_ = org.godhuli.rhipe.RMRHeaderProtos.RhipeMode.MAPPER;
      public boolean hasRHIPEWHAT() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.godhuli.rhipe.RMRHeaderProtos.RhipeMode getRHIPEWHAT() {
        return rHIPEWHAT_;
      }
      public Builder setRHIPEWHAT(org.godhuli.rhipe.RMRHeaderProtos.RhipeMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        rHIPEWHAT_ = value;
        onChanged();
        return this;
      }
      public Builder clearRHIPEWHAT() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rHIPEWHAT_ = org.godhuli.rhipe.RMRHeaderProtos.RhipeMode.MAPPER;
        onChanged();
        return this;
      }
      
      // optional string RHIPELOGFILE = 3;
      private java.lang.Object rHIPELOGFILE_ = "";
      public boolean hasRHIPELOGFILE() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getRHIPELOGFILE() {
        java.lang.Object ref = rHIPELOGFILE_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rHIPELOGFILE_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRHIPELOGFILE(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rHIPELOGFILE_ = value;
        onChanged();
        return this;
      }
      public Builder clearRHIPELOGFILE() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rHIPELOGFILE_ = getDefaultInstance().getRHIPELOGFILE();
        onChanged();
        return this;
      }
      void setRHIPELOGFILE(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        rHIPELOGFILE_ = value;
        onChanged();
      }
      
      // optional string rhipe_outputformat_class = 12;
      private java.lang.Object rhipeOutputformatClass_ = "";
      public boolean hasRhipeOutputformatClass() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getRhipeOutputformatClass() {
        java.lang.Object ref = rhipeOutputformatClass_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rhipeOutputformatClass_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRhipeOutputformatClass(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        rhipeOutputformatClass_ = value;
        onChanged();
        return this;
      }
      public Builder clearRhipeOutputformatClass() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rhipeOutputformatClass_ = getDefaultInstance().getRhipeOutputformatClass();
        onChanged();
        return this;
      }
      void setRhipeOutputformatClass(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        rhipeOutputformatClass_ = value;
        onChanged();
      }
      
      // optional .CombinerMode rhipe_combiner = 13;
      private org.godhuli.rhipe.RMRHeaderProtos.CombinerMode rhipeCombiner_ = org.godhuli.rhipe.RMRHeaderProtos.CombinerMode.NO_COMBINER;
      public boolean hasRhipeCombiner() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public org.godhuli.rhipe.RMRHeaderProtos.CombinerMode getRhipeCombiner() {
        return rhipeCombiner_;
      }
      public Builder setRhipeCombiner(org.godhuli.rhipe.RMRHeaderProtos.CombinerMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        rhipeCombiner_ = value;
        onChanged();
        return this;
      }
      public Builder clearRhipeCombiner() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rhipeCombiner_ = org.godhuli.rhipe.RMRHeaderProtos.CombinerMode.NO_COMBINER;
        onChanged();
        return this;
      }
      
      // optional int32 rhipe_map_buff_size = 14;
      private int rhipeMapBuffSize_ ;
      public boolean hasRhipeMapBuffSize() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getRhipeMapBuffSize() {
        return rhipeMapBuffSize_;
      }
      public Builder setRhipeMapBuffSize(int value) {
        bitField0_ |= 0x00000020;
        rhipeMapBuffSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearRhipeMapBuffSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rhipeMapBuffSize_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 rhipe_map_bytes_read = 15;
      private int rhipeMapBytesRead_ ;
      public boolean hasRhipeMapBytesRead() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getRhipeMapBytesRead() {
        return rhipeMapBytesRead_;
      }
      public Builder setRhipeMapBytesRead(int value) {
        bitField0_ |= 0x00000040;
        rhipeMapBytesRead_ = value;
        onChanged();
        return this;
      }
      public Builder clearRhipeMapBytesRead() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rhipeMapBytesRead_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .ParameterPair serialized_assignments = 16;
      private java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> serializedAssignments_ =
        java.util.Collections.emptyList();
      private void ensureSerializedAssignmentsIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          serializedAssignments_ = new java.util.ArrayList<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair>(serializedAssignments_);
          bitField0_ |= 0x00000080;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.godhuli.rhipe.RMRHeaderProtos.ParameterPair, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder, org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> serializedAssignmentsBuilder_;
      
      public java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> getSerializedAssignmentsList() {
        if (serializedAssignmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(serializedAssignments_);
        } else {
          return serializedAssignmentsBuilder_.getMessageList();
        }
      }
      public int getSerializedAssignmentsCount() {
        if (serializedAssignmentsBuilder_ == null) {
          return serializedAssignments_.size();
        } else {
          return serializedAssignmentsBuilder_.getCount();
        }
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getSerializedAssignments(int index) {
        if (serializedAssignmentsBuilder_ == null) {
          return serializedAssignments_.get(index);
        } else {
          return serializedAssignmentsBuilder_.getMessage(index);
        }
      }
      public Builder setSerializedAssignments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair value) {
        if (serializedAssignmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.set(index, value);
          onChanged();
        } else {
          serializedAssignmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSerializedAssignments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder builderForValue) {
        if (serializedAssignmentsBuilder_ == null) {
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.set(index, builderForValue.build());
          onChanged();
        } else {
          serializedAssignmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSerializedAssignments(org.godhuli.rhipe.RMRHeaderProtos.ParameterPair value) {
        if (serializedAssignmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.add(value);
          onChanged();
        } else {
          serializedAssignmentsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSerializedAssignments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair value) {
        if (serializedAssignmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.add(index, value);
          onChanged();
        } else {
          serializedAssignmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSerializedAssignments(
          org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder builderForValue) {
        if (serializedAssignmentsBuilder_ == null) {
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.add(builderForValue.build());
          onChanged();
        } else {
          serializedAssignmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSerializedAssignments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder builderForValue) {
        if (serializedAssignmentsBuilder_ == null) {
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.add(index, builderForValue.build());
          onChanged();
        } else {
          serializedAssignmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSerializedAssignments(
          java.lang.Iterable<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> values) {
        if (serializedAssignmentsBuilder_ == null) {
          ensureSerializedAssignmentsIsMutable();
          super.addAll(values, serializedAssignments_);
          onChanged();
        } else {
          serializedAssignmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSerializedAssignments() {
        if (serializedAssignmentsBuilder_ == null) {
          serializedAssignments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          serializedAssignmentsBuilder_.clear();
        }
        return this;
      }
      public Builder removeSerializedAssignments(int index) {
        if (serializedAssignmentsBuilder_ == null) {
          ensureSerializedAssignmentsIsMutable();
          serializedAssignments_.remove(index);
          onChanged();
        } else {
          serializedAssignmentsBuilder_.remove(index);
        }
        return this;
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder getSerializedAssignmentsBuilder(
          int index) {
        return getSerializedAssignmentsFieldBuilder().getBuilder(index);
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder getSerializedAssignmentsOrBuilder(
          int index) {
        if (serializedAssignmentsBuilder_ == null) {
          return serializedAssignments_.get(index);  } else {
          return serializedAssignmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
           getSerializedAssignmentsOrBuilderList() {
        if (serializedAssignmentsBuilder_ != null) {
          return serializedAssignmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(serializedAssignments_);
        }
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder addSerializedAssignmentsBuilder() {
        return getSerializedAssignmentsFieldBuilder().addBuilder(
            org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDefaultInstance());
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder addSerializedAssignmentsBuilder(
          int index) {
        return getSerializedAssignmentsFieldBuilder().addBuilder(
            index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDefaultInstance());
      }
      public java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder> 
           getSerializedAssignmentsBuilderList() {
        return getSerializedAssignmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.godhuli.rhipe.RMRHeaderProtos.ParameterPair, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder, org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
          getSerializedAssignmentsFieldBuilder() {
        if (serializedAssignmentsBuilder_ == null) {
          serializedAssignmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.godhuli.rhipe.RMRHeaderProtos.ParameterPair, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder, org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder>(
                  serializedAssignments_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          serializedAssignments_ = null;
        }
        return serializedAssignmentsBuilder_;
      }
      
      // repeated .ParameterPair arguments = 17;
      private java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> arguments_ =
        java.util.Collections.emptyList();
      private void ensureArgumentsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          arguments_ = new java.util.ArrayList<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair>(arguments_);
          bitField0_ |= 0x00000100;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.godhuli.rhipe.RMRHeaderProtos.ParameterPair, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder, org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> argumentsBuilder_;
      
      public java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> getArgumentsList() {
        if (argumentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arguments_);
        } else {
          return argumentsBuilder_.getMessageList();
        }
      }
      public int getArgumentsCount() {
        if (argumentsBuilder_ == null) {
          return arguments_.size();
        } else {
          return argumentsBuilder_.getCount();
        }
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair getArguments(int index) {
        if (argumentsBuilder_ == null) {
          return arguments_.get(index);
        } else {
          return argumentsBuilder_.getMessage(index);
        }
      }
      public Builder setArguments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair value) {
        if (argumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentsIsMutable();
          arguments_.set(index, value);
          onChanged();
        } else {
          argumentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setArguments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder builderForValue) {
        if (argumentsBuilder_ == null) {
          ensureArgumentsIsMutable();
          arguments_.set(index, builderForValue.build());
          onChanged();
        } else {
          argumentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addArguments(org.godhuli.rhipe.RMRHeaderProtos.ParameterPair value) {
        if (argumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentsIsMutable();
          arguments_.add(value);
          onChanged();
        } else {
          argumentsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addArguments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair value) {
        if (argumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentsIsMutable();
          arguments_.add(index, value);
          onChanged();
        } else {
          argumentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addArguments(
          org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder builderForValue) {
        if (argumentsBuilder_ == null) {
          ensureArgumentsIsMutable();
          arguments_.add(builderForValue.build());
          onChanged();
        } else {
          argumentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addArguments(
          int index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder builderForValue) {
        if (argumentsBuilder_ == null) {
          ensureArgumentsIsMutable();
          arguments_.add(index, builderForValue.build());
          onChanged();
        } else {
          argumentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllArguments(
          java.lang.Iterable<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPair> values) {
        if (argumentsBuilder_ == null) {
          ensureArgumentsIsMutable();
          super.addAll(values, arguments_);
          onChanged();
        } else {
          argumentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearArguments() {
        if (argumentsBuilder_ == null) {
          arguments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          argumentsBuilder_.clear();
        }
        return this;
      }
      public Builder removeArguments(int index) {
        if (argumentsBuilder_ == null) {
          ensureArgumentsIsMutable();
          arguments_.remove(index);
          onChanged();
        } else {
          argumentsBuilder_.remove(index);
        }
        return this;
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder getArgumentsBuilder(
          int index) {
        return getArgumentsFieldBuilder().getBuilder(index);
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder getArgumentsOrBuilder(
          int index) {
        if (argumentsBuilder_ == null) {
          return arguments_.get(index);  } else {
          return argumentsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
           getArgumentsOrBuilderList() {
        if (argumentsBuilder_ != null) {
          return argumentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arguments_);
        }
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder addArgumentsBuilder() {
        return getArgumentsFieldBuilder().addBuilder(
            org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDefaultInstance());
      }
      public org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder addArgumentsBuilder(
          int index) {
        return getArgumentsFieldBuilder().addBuilder(
            index, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.getDefaultInstance());
      }
      public java.util.List<org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder> 
           getArgumentsBuilderList() {
        return getArgumentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.godhuli.rhipe.RMRHeaderProtos.ParameterPair, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder, org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder> 
          getArgumentsFieldBuilder() {
        if (argumentsBuilder_ == null) {
          argumentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.godhuli.rhipe.RMRHeaderProtos.ParameterPair, org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder, org.godhuli.rhipe.RMRHeaderProtos.ParameterPairOrBuilder>(
                  arguments_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          arguments_ = null;
        }
        return argumentsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:RMRHeader)
    }
    
    static {
      defaultInstance = new RMRHeader(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RMRHeader)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ParameterPair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ParameterPair_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RMRHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RMRHeader_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017RMRHeader.proto\",\n\rParameterPair\022\014\n\004na" +
      "me\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"\243\002\n\tRMRHeader\022\n\n" +
      "\002ID\030\001 \002(\t\022\035\n\tRHIPEWHAT\030\002 \001(\0162\n.RhipeMode" +
      "\022\024\n\014RHIPELOGFILE\030\003 \001(\t\022 \n\030rhipe_outputfo" +
      "rmat_class\030\014 \001(\t\022%\n\016rhipe_combiner\030\r \001(\016" +
      "2\r.CombinerMode\022\033\n\023rhipe_map_buff_size\030\016" +
      " \001(\005\022\034\n\024rhipe_map_bytes_read\030\017 \001(\005\022.\n\026se" +
      "rialized_assignments\030\020 \003(\0132\016.ParameterPa" +
      "ir\022!\n\targuments\030\021 \003(\0132\016.ParameterPair*$\n" +
      "\tRhipeMode\022\n\n\006MAPPER\020\001\022\013\n\007REDUCER\020\002*1\n\014C",
      "ombinerMode\022\017\n\013NO_COMBINER\020\000\022\020\n\014USE_COMB" +
      "INER\020\001B$\n\021org.godhuli.rhipeB\017RMRHeaderPr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ParameterPair_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ParameterPair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ParameterPair_descriptor,
              new java.lang.String[] { "Name", "Value", },
              org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.class,
              org.godhuli.rhipe.RMRHeaderProtos.ParameterPair.Builder.class);
          internal_static_RMRHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RMRHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RMRHeader_descriptor,
              new java.lang.String[] { "ID", "RHIPEWHAT", "RHIPELOGFILE", "RhipeOutputformatClass", "RhipeCombiner", "RhipeMapBuffSize", "RhipeMapBytesRead", "SerializedAssignments", "Arguments", },
              org.godhuli.rhipe.RMRHeaderProtos.RMRHeader.class,
              org.godhuli.rhipe.RMRHeaderProtos.RMRHeader.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
